export const portfolio = {
  profile: {
    name: 'Jungwok Park',
    role: 'Frontend Engineer',
    intro: '복잡한 제품 경험을 명확한 인터페이스로 바꾸고, 성능과 디테일까지 책임지는 프론트엔드 개발자입니다.',
    experience: '4 Years',
    availability: 'Open to new opportunities',
  },
  stats: [
    { value: '4+', label: 'Years building products' },
    { value: '12+', label: 'Projects shipped' },
    { value: '∞', label: 'Curiosity for the web' },
  ],
  skills: [
    {
      name: 'React',
      category: 'Interface',
      description: 'Hook Form, Tailwind CSS, Zustand, TanStack Query를 활용한 확장 가능한 UI 설계',
      color: '#7dd3fc',
    },
    {
      name: 'Next.js',
      category: 'Framework',
      description: '앱 라우팅, SSR(프록시, 다국어처리, 테마), 이미지 최적화를 고려한 제품 개발',
      color: '#f8fafc',
    },
    {
      name: 'TypeScript',
      category: 'Language',
      description: '도메인 모델과 API 경계를 명확히 만드는 타입 중심 개발',
      color: '#60a5fa',
    },
    {
      name: 'Expo',
      category: 'Mobile',
      description: 'React Native와 Expo를 활용한 네이티브/하이브리드 앱 개발',
      color: '#c4b5fd',
    },
    {
      name: 'AWS',
      category: 'Cloud',
      description: 'S3, CloudFront, Route53, Amplify를 연결한 서비스 아키텍처 구축',
      color: '#fbbf24',
    },
    {
      name: 'Docker',
      category: 'Platform',
      description: '도커 이미지 컨테이너 빌드로 CI/CD 파이프라인 구성',
      color: '#38bdf8',
    },
  ],
  career: [
    {
      period: '2024 — Now',
      company: '(주) 에이엠랩스',
      role: 'Frontend Developer',
      summary: '제품의 핵심 웹 경험과 디자인 시스템을 개발하고 성능 지표를 개선했습니다.',
    },
    {
      period: '2022 — 2024',
      company: '(주) 킨트',
      role: 'Frontend Developer',
      summary: 'React와 Next.js 기반 서비스의 신규 기능 개발과 운영 안정화를 담당했습니다.',
    },
  ],
  projects: [
    {
      index: '01',
      name: 'Treat',
      type: '모바일 앱',
      description: '실시간 연결과 매끄러운 콘텐츠 경험에 집중한 네이티브 앱입니다.',
      impact: 'Realtime interaction · Mobile-first UX',
      stack: ['React Native', 'Expo', 'AWS', 'WebSocket'],
    },
    {
      index: '02',
      name: '마이메디',
      type: '웹 플랫폼',
      description: '대규모 콘텐츠를 빠르게 탐색할 수 있도록 설계한 Next.js 기반 웹 플랫폼입니다.',
      impact: 'Core Web Vitals · Search experience',
      stack: ['Next.js', 'TypeScript', 'TanStack Query', 'Recoil'],
    },
    {
      index: '03',
      name: 'Pulse',
      type: 'Design System',
      description: '제품군 전반의 일관성과 개발 속도를 높인 접근성 중심 디자인 시스템입니다.',
      impact: 'Accessible UI · Faster delivery',
      stack: ['React', 'Storybook', 'Radix UI', 'Chromatic'],
    },
  ],
  architecture: ['Client', 'CloudFront', 'Signed Cookie', 'S3 (HLS)', 'Video'],
  contact: [
    { label: 'Phone', value: '010-3176-0315' },
    { label: 'Address', value: '서울시 영등포구 신풍로 77' },
    { label: 'Email', value: 'jungwook3176@gmail.com' },
    { label: 'GitHub', value: 'https://github.com/JunDemi' },
  ],
  education: [
    { label: 'Phone', value: '010-3176-0315' },
    { label: 'Address', value: '서울시 영등포구 신풍로 77' },
    { label: 'Email', value: 'jungwook3176@gmail.com' },
    { label: 'GitHub', value: 'https://github.com/JunDemi' },
  ],
} as const;

export const destinations = [
  {
    id: 'about',
    label: 'About',
    modelPath: '/mercury.glb',
    color: '#7dd3fc',
    orbitRadius: 1.5,
    initialAngle: 2.65,
    rotateSpeed: 0.234,
    orbitSpeed: 1.0,
    axialTilt: 0.03,
    size: 0.24,
  },
  {
    id: 'career',
    label: 'Career',
    modelPath: '/venus.glb',
    color: '#a78bfa',
    orbitRadius: 2.5,
    initialAngle: 1.9,
    rotateSpeed: 0.08,
    orbitSpeed: 0.72,
    axialTilt: 3.1,
    size: 0.26,
  },
  {
    id: 'skills',
    label: 'Skills',
    modelPath: '/earth.glb',
    color: '#38bdf8',
    orbitRadius: 3.5,
    initialAngle: 0.82,
    rotateSpeed: 0.415,
    orbitSpeed: 0.61,
    axialTilt: 0.41,
    size: 0.28,
  },
  {
    id: 'projects',
    label: 'Projects',
    modelPath: '/mars.glb',
    color: '#fbbf24',
    orbitRadius: 4.5,
    initialAngle: 0,
    rotateSpeed: 0.403,
    orbitSpeed: 0.49,
    axialTilt: 0.44,
    size: 0.28,
  },
  {
    id: 'architecture',
    label: 'Architecture',
    modelPath: '/jupiter.glb',
    color: '#34d399',
    orbitRadius: 5.5,
    initialAngle: -0.74,
    rotateSpeed: 1.0,
    orbitSpeed: 0.25,
    axialTilt: 0.05,
    size: 0.46,
  },
  {
    id: 'gallery',
    label: 'Gallery',
    modelPath: '/saturn.glb',
    color: '#fb7185',
    orbitRadius: 6.5,
    initialAngle: -1.85,
    rotateSpeed: 0.931,
    orbitSpeed: 0.18,
    axialTilt: 0.47,
    size: 0.42,
  },
  {
    id: 'contact',
    label: 'Contact',
    modelPath: '/uranus.glb',
    color: '#e879f9',
    orbitRadius: 7.5,
    initialAngle: -2.72,
    rotateSpeed: 0.576,
    orbitSpeed: 0.13,
    axialTilt: 1.71,
    size: 0.34,
  },
  {
    id: 'education',
    label: 'Education',
    modelPath: '/neptune.glb',
    color: '#f8fafc',
    orbitRadius: 8.5,
    initialAngle: -3.59,
    rotateSpeed: 0.616,
    orbitSpeed: 0.1,
    axialTilt: 0.5,
    size: 0.34,
  },
] as const;