export const portfolio = {
  intro: [
    '복잡한 요구사항을 구조적으로 해결합니다.',
    '빠르고 안정적인 서비스를 지향합니다.',
    '대화와 코드 리뷰를 중요하게 생각합니다.',
  ],
  stats: [
    { value: '4+', label: 'Years of Career' },
    { value: '10+', label: 'Projects Shipped' },
    { value: '20+', label: 'Technologies' },
    { value: '4,000+', label: 'Commits' },
  ],
  skills: [
    {
      name: 'React',
      category: '인터페이스',
      description: '컴포넌트 기반 설계와 Hook 활용을 통한 재사용 가능한 UI 개발 및 상태 관리',
      color: '#7dd3fc',
    },
    {
      name: 'React Native',
      category: '모바일',
      description: 'React Native와 Expo를 활용한 네이티브/하이브리드 앱 개발',
      color: '#88acdb',
    },
    {
      name: 'Next.js',
      category: '프레임워크',
      description: 'App Router 기반 SSR, Middleware, 다국어 처리, 미디어 최적화 활용',
      color: '#f8fafc',
    },
    {
      name: 'TypeScript',
      category: '언어',
      description: '도메인 모델과 API 경계를 명확히 만드는 타입 중심 개발',
      color: '#60a5fa',
    },
    {
      name: 'Tailwind CSS',
      category: '스타일링',
      description: 'CSS-in-JS 대신 클래스 기반 스타일링으로 빠른 개발 속도와 유지보수성 향상',
      color: '#62a6ac',
    },
    {
      name: 'Form',
      category: '사용자 경험',
      description: 'React Hook Form과 Zod를 활용한 입력 검증 및 사용자 친화적인 폼 설계',
      color: '#5a9aee',
    },
    {
      name: 'Data Fetch',
      category: '데이터 관리',
      description: 'TanStack Query 기반 서버 상태 관리와 캐싱 전략으로 효율적인 데이터 처리',
      color: '#efc786',
    },
    {
      name: 'State',
      category: '상태 관리',
      description: 'Zustand와 Redux를 활용한 전역 상태 관리 및 애플리케이션 데이터 흐름 설계',
      color: '#8d60e6',
    },
    {
      name: 'Data View',
      category: '데이터 시각화',
      description: 'D3.js, Chart.js, dnd-kit을 활용한 데이터 시각화와 인터랙티브 UI 설계',
      color: '#4ade80',
    },
    {
      name: 'WebSocket',
      category: '웹소켓',
      description: 'socket.io, stomp.js를 활용한 실시간 양방향 데이터 전송',
      color: '#ffffff',
    },
    {
      name: 'AWS',
      category: '인프라',
      description: 'S3, CloudFront, Route53, Amplify를 연결한 서비스 아키텍처 구축',
      color: '#fbbf24',
    },
    {
      name: 'Docker',
      category: '플랫폼',
      description: 'Docker 기반 애플리케이션 컨테이너화 및 배포 환경 구성',
      color: '#38bdf8',
    },
    {
      name: 'Firebase',
      category: 'DB, 스토리지',
      description: 'Firebase Authentication, Firestore 기반 인증 및 실시간 데이터 관리',
      color: '#fc5353',
    },
    {
      name: 'Framer Motion',
      category: '애니메이션',
      description: 'Framer Motion을 활용한 다이다믹 UI 구현',
      color: '#ffffff',
    },
    {
      name: 'AI Dev',
      category: 'AI Tools',
      description: 'Cursor Pro, Claude Code, Codex를 활용한 코드 생성, 리팩토링, 디버깅 및 개발 생산성 향상',
      color: '#919191',
    },
    {
      name: 'AI Workflow',
      category: 'AI Tools',
      description: 'AI Agent를 활용한 요구사항 분석, 설계 검토, 반복 작업 자동화 및 프로토타이핑',
      color: '#f23dbf',
    },
  ],
  career: [
    {
      period: '2024 — Now',
      company: '(주) 에이엠랩스',
      role: '소프트웨어 개발 · IT 솔루션 ·  웹/모바일 개발',
      summary: [
        'React/Next.js 기반 서비스 개발 및 운영 안정화/유지보수',
        '웹뷰 기반 하이브리드 앱 개발(Expo, Flutter)',
        '대용량 미디어 파일 및 비디오 스트리밍 서비스(HLS) 개발',
        'CloudFront, S3, Route53, Amplify를 활용한 서비스 인프라 세팅',
      ],
    },
    {
      period: '2022 — 2024',
      company: '(주) 킨트',
      role: '웹서비스 개발 · SI · B2B ',
      summary: [
        'React/Next.js 기반 서비스 개발 및 운영 안정화/유지보수',
        'Prisma(ORM), PlanetScale(DB), Firebase(Auth)를 활용한 풀스택 개발',
        'Framer Motion을 활용한 다이다믹 UI 구현',
        '초보 개발자들을 위한 프론트엔드 개발 가이드',
      ],
    },
  ],
  projects: [
    {
      index: '01',
      name: 'Treat',
      type: '모바일 앱',
      description: '인터랙티브 트레이딩 플랫폼',
      impact: 'Social Login · Demo Trade',
      stack: ['React Native', 'Expo', 'Zustand', 'AWS', 'Firebase Messaging'],
    },
    {
      index: '02',
      name: '마이메디',
      type: '웹 플랫폼',
      description: '대규모 콘텐츠를 빠르게 탐색할 수 있도록 설계한 웹 플랫폼입니다.',
      impact: 'Medical Report · Health Care',
      stack: ['Next.js', 'Context API', 'AWS', 'Styled Components'],
    },
    {
      index: '03',
      name: 'Pick It',
      type: '웹 플랫폼',
      description: '제품군 전반의 일관성과 개발 속도를 높인 접근성 중심 디자인 시스템입니다.',
      impact: 'Accessible UI · Faster delivery',
      stack: ['React', 'Redux', 'SCSS', 'Firebase'],
    },
  ],
  architecture: ['Client', 'CloudFront', 'Signed Cookie', 'S3 (HLS)', 'Video'],
  contact: [
    { label: 'Phone', value: '010-3176-0315' },
    { label: 'Address', value: '서울시 영등포구' },
    { label: 'Email', value: 'jungwook3176@gmail.com' },
    { label: 'GitHub', value: 'https://github.com/JunDemi' },
  ],
  guestbook: [
    { label: 'Phone', value: '010-3176-0315' },
    { label: 'Address', value: '서울시 영등포구' },
    { label: 'Email', value: 'jungwook3176@gmail.com' },
    { label: 'GitHub', value: 'https://github.com/JunDemi' },
  ],
} as const;

export const destinations = [
  {
    id: 'about',
    label: 'About',
    modelPath: '/planet/mercury.glb',
    color: '#A7A7A7',
    orbitRadius: 1.5,
    initialAngle: 2.65,
    rotateSpeed: 0.234,
    orbitSpeed: 1.0,
    axialTilt: 0.03,
    size: 0.24,
  },
  {
    id: 'career',
    label: 'Career',
    modelPath: '/planet/venus.glb',
    color: '#E6C27A',
    orbitRadius: 2.5,
    initialAngle: 1.9,
    rotateSpeed: 0.08,
    orbitSpeed: 0.72,
    axialTilt: 3.1,
    size: 0.26,
  },
  {
    id: 'skills',
    label: 'Skills',
    modelPath: '/planet/earth.glb',
    color: '#2E7DE9',
    orbitRadius: 3.5,
    initialAngle: 0.82,
    rotateSpeed: 0.415,
    orbitSpeed: 0.61,
    axialTilt: 0.41,
    size: 0.28,
  },
  {
    id: 'projects',
    label: 'Projects',
    modelPath: '/planet/mars.glb',
    color: '#C1440E',
    orbitRadius: 4.5,
    initialAngle: 0,
    rotateSpeed: 0.403,
    orbitSpeed: 0.49,
    axialTilt: 0.44,
    size: 0.28,
  },
  {
    id: 'architecture',
    label: 'Architecture',
    modelPath: '/planet/jupiter.glb',
    color: '#D89A5A',
    orbitRadius: 5.5,
    initialAngle: -0.74,
    rotateSpeed: 1.0,
    orbitSpeed: 0.25,
    axialTilt: 0.05,
    size: 0.46,
  },
  {
    id: 'gallery',
    label: 'Gallery',
    modelPath: '/planet/saturn.glb',
    color: '#E8D39E',
    orbitRadius: 6.5,
    initialAngle: -1.85,
    rotateSpeed: 0.931,
    orbitSpeed: 0.18,
    axialTilt: 0.47,
    size: 0.42,
  },
  {
    id: 'contact',
    label: 'Contact',
    modelPath: '/planet/uranus.glb',
    color: '#74D7E8',
    orbitRadius: 7.5,
    initialAngle: -2.72,
    rotateSpeed: 0.576,
    orbitSpeed: 0.13,
    axialTilt: 1.71,
    size: 0.34,
  },
  {
    id: 'guestbook',
    label: 'Guestbook',
    modelPath: '/planet/neptune.glb',
    color: '#3A6FF7',
    orbitRadius: 8.5,
    initialAngle: -3.59,
    rotateSpeed: 0.616,
    orbitSpeed: 0.1,
    axialTilt: 0.5,
    size: 0.34,
  },
] as const;
